import type { Metadata } from "next";
import "./globals.css";
import { MyProvider } from "../Redux/provider";

export const metadata: Metadata = {
  title: {
    default : "Online Education",
    template : "%s"
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen w-full overflow-x-hidden overflow-y-scroll">
          <MyProvider child = {children} />
      </body>
    </html>
  );
}
